### ISSUE TITLE
image_slicer is a dead project

### ISSUE THREAD

**Issue by hemna** [qvarforth/trackdirect#42]
I'm trying to install the requirements.txt in a virtual env and it's failing on an ancient pillow version which is specified by the image_slicer project.   It looks like the image_slicer project is now defunct and put into archive mode in march of 2023.

https://github.com/samdobson/image_slicer

The last release was in 2020 on pypi.  

```
└─> pip install image_slicer
Collecting image_slicer
  Using cached image_slicer-2.1.1-py2.py3-none-any.whl (8.3 kB)
Collecting Pillow==7.2.0 (from image_slicer)
  Using cached Pillow-7.2.0.tar.gz (39.1 MB)
  Preparing metadata (setup.py) ... done
.........


      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/2k/x4lk8j0n701_z8j8dr5f8yx00000gn/T/pip-install-wucwy0q3/pillow_938c6b91237b49df910c09b4adaef2fe/setup.py", line 918, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects
code-stats-zsh: Received 5 consecutive errors when trying to save XP. Stopping.
```
that version of Pillow is very old and won't run on modern python 3 versions.

**Comment by hemna** [comment]
I can't seem to install trackdirect now on the latest ubuntu or macos because of this error.

**Comment by F4FXL** [comment]
I had success on Debian 12, needed a lot of tinkering though... No issues with image_slicer

**Comment by qvarforth** [comment]
image_slicer is not used by trackdirect any more. closing this issue.

**Comment by hemna** [comment]
Confirmed installing the requirements from requirements.txt works on macos.
